ALTER TABLE IF EXISTS booking_session
ADD COLUMN IF NOT EXISTS guest_type TEXT DEFAULT('LOCAL');

ALTER TABLE IF EXISTS booking
ADD COLUMN IF NOT EXISTS guest_type TEXT DEFAULT('LOCAL');

ALTER TABLE IF EXISTS tentative_booking
ADD COLUMN IF NOT EXISTS guest_type TEXT DEFAULT('LOCAL');