CREATE TABLE hotel_special_offer(
	id SERIAL PRIMARY KEY,
	hotel_id INTEGER REFERENCES hotel(id),
	title TEXT,
	description TEXT,
	minimum_check_in_date DATE,
	maximum_check_out_date DATE,
	start_booking_date DATE,
	end_booking_date DATE,
	is_active BOOLEAN,
	is_reviewed BOOLEAN,
	short_message_en TEXT,
	short_message_my TEXT,
	full_message_en TEXT,
	full_message_my TEXT,
	is_applied_to_all_room_types BOOLEAN,
	applied_room_type_ids INTEGER[],
	messages_by_room_types JSON,
	created_by INTEGER REFERENCES user_account(id),
	created_at TIMESTAMP,
	updated_by INTEGER REFERENCES user_account(id),
	updated_at TIMESTAMP
);