ALTER TABLE IF EXISTS booking ALTER COLUMN checkin_date DROP NOT NULL;

ALTER TABLE IF EXISTS booking ALTER COLUMN checkout_date DROP NOT NULL;

ALTER TABLE IF EXISTS booking ALTER COLUMN primary_guest_id DROP NOT NULL;

ALTER TABLE IF EXISTS booking ALTER COLUMN booker_id DROP NOT NULL;

ALTER TABLE IF EXISTS booking ALTER COLUMN payment_id DROP NOT NULL;